"""empty message

Revision ID: 69bebe2db35c
Revises: 81baf171e80b
Create Date: 2016-08-26 21:00:49.727423

"""

# revision identifiers, used by Alembic.
revision = '69bebe2db35c'
down_revision = '81baf171e80b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
