"""empty message

Revision ID: 86010b95e634
Revises: 8b65c64d8160
Create Date: 2016-08-15 22:09:05.096361

"""

# revision identifiers, used by Alembic.
revision = '86010b95e634'
down_revision = '8b65c64d8160'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
